meta_product_name: "PlaySync"
meta_title: "PlaySync - Product tagline"
meta_description: "An app where you can find gamers to play games together"
meta_image: "playsync-logo.png" # should exist in `app/assets/images/`
